name: Lint, Test
on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:
jobs:
  generate-matrix:
    name: Generate Job Matrix
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.mx }}
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.21.4'
      - id: set-matrix
        run: |
          echo "mx=$(go run main.go generate-matrix)" >> $GITHUB_OUTPUT # into file $GITHUB_OUTPUT append line mx=...
  lint:
    name: Check ${{ matrix.project }}
    runs-on: ubuntu-latest
    if: needs.generate-matrix.outputs.matrix != ''
    needs: [generate-matrix]
    strategy:
      fail-fast: false
      max-parallel: 6
      matrix: ${{fromJSON(needs.generate-matrix.outputs.matrix)}}

    steps:
      - uses: actions/checkout@v4
      - run: echo ${{ matrix.config }}
    # TODO: investigate why actions are not executed from matrix!
    # TODO: start with no-json