name: Lint, Test
on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:
jobs:
  generate-matrix:
    name: Generate Job Matrix
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.21.4'
      - id: set-matrix
        run: go run main.go generate-matrix
  test:
    name: Check ${{ matrix.nickname }}
    runs-on: ubuntu-latest
    if: needs.generate-matrix.outputs.matrix != ''
    needs: [generate-matrix]
    strategy:
      fail-fast: false
      max-parallel: 6
      matrix: ${{fromJSON(needs.generate-matrix.outputs.matrix)}}

    steps:
      - uses: actions/checkout@v3
      - run: echo ${{ matrix.package }}
